#pragma once

#include "Define.h" 

enum class QuestStageFlags : uint32
{
    FELENDREN_MET,
    FELENDREN_KILLED,
    FELENDREN_PUT_DOWN,
    FELENDREN_TALKED_6,
    SHRINE_OF_DATHREMAR_READ,
    SOLANIANS_SCRYING_ORB_FOUND,
    SCOLL_OF_SCOURGE_MAGIC_FOUND,
    SOLANIANS_JOURNAL_FOUND,
    SOLANIANS_SCRYING_ORB_CONSUMED,
    SCOLL_OF_SCOURGE_MAGIC_CONSUMED,
    SOLANIANS_JOURNAL_CONSUMED,
};
